-- ====================================================
-- SEED: Carga inicial de prestadores - Ninho Verde 1
-- Execute APÓS o schema.sql
-- ====================================================

-- Inserir todos os prestadores do arquivo real
INSERT INTO public.prestadores (nome, telefone, area_atuacao, obs_positiva, obs_negativa) VALUES
-- ÁGUA / GÁS / GELO
('ROGÉRIO', '15 99133-5780', 'Água/Gás/Gelo', 'BEM RECOMENDADO, FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
('JOÃO CARLOS - MORADOR', '15 99101-2261', 'Água/Gás/Gelo', 'BEM RECOMENDADO, FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
('ARMAZEM FOGAÇA', '15 99677-5717', 'Água/Gás/Gelo', 'BEM RECOMENDADO, FAZ ENTREGA AGENDADA', 'NENHUMA RECLAMAÇÃO'),
('FELIPE', '15 99752-8094', 'Água/Gás/Gelo', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('VAL', '14 99163-0913', 'Água/Gás/Gelo', 'BEM RECOMENDADO (ENCHE PISCINA)', 'NENHUMA RECLAMAÇÃO'),
('GENÃO', '15 99656-4592', 'Água/Gás/Gelo', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('RANCHO DO ALEMÃO', '15 99637-5671', 'Água/Gás/Gelo', 'BEM RECOMENDADO, FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
-- ALARME
('SPACE ALARMES', '15 99774-4789', 'Alarme/Câmeras', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('EDUARDO DIOGO', '11 94514-8059', 'Alarme/Câmeras', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ELETROTECH - ELVIS', '15 98803-3907', 'Alarme/Câmeras', '', 'GRANDE PREJUÍZO FINANCEIRO AO PROPRIETÁRIO'),
('MGM', '15 99730-4422', 'Alarme/Câmeras', 'DIVERSOS ATENDIMENTOS NO NINHO', '5 RECLAMAÇÕES'),
('LUCAS CREVILARI', '15 99752-9459', 'Alarme/Câmeras', 'BEM RECOMENDADO, PREÇO JUSTO', 'NENHUMA RECLAMAÇÃO'),
('ITEC TELECOM - DANILO', '15 99754-8857', 'Alarme/Câmeras', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- ALIMENTOS
('ART''S GOURMET PRISCILA ALEIXO', '15 99622-7707', 'Alimentos/Confeitaria', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('DELÍCIAS DA FÊ - FERNANDA DADATTO', '15 99738-7278', 'Alimentos/Confeitaria', 'MUITO BEM RECOMENDADA - FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
('CONFEITARIA AMANDA NUNES', '15 99622-3366', 'Alimentos/Confeitaria', 'MUITO BEM RECOMENDADA, FICA EM CESÁRIO LANGE', 'NENHUMA RECLAMAÇÃO'),
('DÉBORA RODRIGUES', '15 99770-5229', 'Alimentos/Confeitaria', 'MUITO BEM RECOMENDADA, FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
('REGINA LOBO - REGINA DOCES & CIA', '15 99715-4188', 'Alimentos/Confeitaria', 'MUITO BEM RECOMENDADA, FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
('EMPORIO DA CARNE', '15 99815-6799', 'Alimentos/Carnes', 'MUITO BEM RECOMENDADA, FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
('KÁTIA - GT16 - MORADORA', '15 99185-2566', 'Alimentos/Hortifruti', 'MUITO BEM RECOMENDADA, FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
('ADEGA DO NINÃO', '11 98193-1444', 'Alimentos/Feijoada', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('BAR DO FELIPÃO', '15 99272-6866', 'Alimentos/Feijoada', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('MARIÚCHA - MORADORA', '15 99837-3855', 'Alimentos/Feijoada', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('NORMA MORADORA', '11 98025-7794', 'Alimentos/Feijoada', 'BEM RECOMENDADA, NÃO FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
('RECANTO BAIANO', '11 96370-3965', 'Alimentos/Feijoada', 'BEM RECOMENDADA, FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
('IVONETE', '15 99707-3595', 'Alimentos/Frango Assado', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('SÍTIO DO LOBO', '15 99747-3916', 'Alimentos/Hortifruti', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('LANE', '15 99275-9251', 'Alimentos/Queijos/Laticínios', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('Q''GOSTOSURA', '15 99829-8943', 'Alimentos/Lanches', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ROTA 79 HAMBURGUERIA', '15 99804-0703', 'Alimentos/Lanches', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('PATRÍCIA/EUNICE - MORADORAS', '11 95520-8655', 'Alimentos/Massas', 'MUITO BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('MAVPAM CLEIDE', '11 97832-3440', 'Alimentos/Pães Artesanais', 'BEM RECOMENDADA, VEM AOS SÁBADOS', 'NENHUMA RECLAMAÇÃO'),
('DONA AURORA', '11 94112-1346', 'Alimentos/Pastéis', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('BORDO DORATTO', '15 99141-1180', 'Alimentos/Pizzaria', 'MUITO BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('CLUBE SLIM NINHO VERDE / FLÁVIA', '15 99198-4617', 'Alimentos/Pizzaria', 'MUITO BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('NAJARAS', '15 98171-6190', 'Alimentos/Pizzaria', 'BEM RECOMENDADA, FAZ ENTREGA', 'ALGUMAS RECLAMAÇÕES'),
('PIZZARIA E ESFIHARIA PAULISTA', '15 99677-1177', 'Alimentos/Pizzaria', 'MUITO BEM RECOMENDADA, FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
('DIVINAS TORTAS - MÔNICA', '11 96405-1671', 'Alimentos/Tortas', 'MUITO BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
-- SERVIÇOS TÉCNICOS
('EVALDO', '15 99766-3877', 'Antenista/Alarme', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('MSOL-DENIS', '15 98829-0783', 'Aquecedor Solar', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ALEXANDRE - MASTERSOL', '15 99825-2266', 'Aquecedor Solar', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('NANDO', '14 99805-2071', 'Aquecimento de Piscina', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ELVISELETROTECH', '15 98803-0001', 'Ar Condicionado', '', 'PEGOU O DINHEIRO, SÓ ENROLOU, NÃO RESOLVEU. NÃO ATENDE MAIS.'),
('SÓ AR - LUIZINHO FERREIRA', '15 99794-4247', 'Ar Condicionado', 'BEM RECOMENDADO PARA AR, ELÉTRICA E HIDRÁULICA', 'NENHUMA RECLAMAÇÃO'),
('THIAGO', '15 99841-6919', 'Ar Condicionado', 'BEM RECOMENDADO, COMPETENTE, CUIDADOSO', 'NENHUMA RECLAMAÇÃO'),
('EZAKI-VANDERLAN', '11 98606-6057', 'Ar Condicionado', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('LUCIOTEC - ÍTALO', '15 99640-4936', 'Ar Condicionado', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- ARQUITETURA / ENGENHARIA
('IGOR', '15 99848-6238', 'Arquitetura', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ISABELA FERRAREZI', '15 99661-2083', 'Arquitetura', 'FEZ AS PLANTAS DE MUITOS MORADORES, MUITO REQUISITADA', 'NENHUMA RECLAMAÇÃO'),
('LUCIANA COSTA', '15 99114-8305', 'Arquitetura', 'BEM RECOMENDADA, PROJETO SUSTENTÁVEL', 'NENHUMA RECLAMAÇÃO'),
('RENAN', '11 96410-4326', 'Arquitetura', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('MARCOS LUIZ', '11 96909-1075', 'Arquitetura', 'ALTO PADRÃO ALPHAVILLE, SEM OBRA AINDA NO NINHO', ''),
('ENGENHEIRO FERNANDO FOGAÇA', '15 99728-8271', 'Engenharia', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ENGENHEIRO MATHEUS CASTRO', '15 98109-2419', 'Engenharia', 'BEM RECOMENDADO PARA PROJETO ESTRUTURAL, HIDRÁULICO E ELÉTRICO', 'NENHUMA RECLAMAÇÃO'),
('ENGENHEIRO MICHEL FERNANDES', '14 99817-8644', 'Engenharia', 'BEM RECOMENDADO PARA TOPOGRAFIA E SONDAGEM', 'NENHUMA RECLAMAÇÃO'),
-- BEBIDAS
('ADEGA AVENIDA - PORANGABA', '15 99160-2578', 'Bebidas', 'BEM RECOMENDADO - FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
('ADEGA DO ALEMÃO - PORANGABA', '15 99788-8380', 'Bebidas', 'BEM RECOMENDADO, FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
('ARMAZÉM DAS BEBIDAS - PORANGABA', '15 98171-3105', 'Bebidas', 'BEM RECOMENDADO, FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
('SERTÃO BEBIDAS - CESÁRIO LANGE', '15 99711-5334', 'Bebidas', 'BEM RECOMENDADO, FAZ ENTREGA', 'NENHUMA RECLAMAÇÃO'),
-- PISCINAS
('WILSON', '15 99764-9285', 'Bombas de Piscina', 'BEM RECOMENDADO, PREÇO JUSTO E HONESTO', 'NENHUMA RECLAMAÇÃO'),
('LUIZ BARONE', '11 94739-7642', 'Bombas de Piscina', 'BEM RECOMENDADO NO INÍCIO', 'BOMBAS PEGARAM FOGO APÓS CONSERTO, VAZAMENTOS, PREÇO ALTO'),
('JÚ PISCINAS', '15 99184-2107', 'Piscinas/Construção', '', 'SUMIRAM APÓS FAZER APENAS ALVENARIA'),
-- ESTÉTICA
('STÚDIO SABLEVICIUS', '15 99619-0062', 'Estética/Cabeleireira', 'TRATAMENTO CAPILAR, BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('NANDA LUNAS', '15 99686-5054', 'Estética/Cabeleireira', 'ATENDE DENTRO DO NV, EXCELENTE PROFISSIONAL', 'NENHUMA RECLAMAÇÃO'),
('RAQUEL - MORADORA', '15 99784-2670', 'Estética/Cabeleireira', 'BEM RECOMENDADA (UNHAS DE GEL)', 'NENHUMA RECLAMAÇÃO'),
-- CAÇAMBAS E ENTULHO
('ANDRADE CAÇAMBAS', '15 99620-1096', 'Caçambas', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('KATA ENTULHO', '15 97402-8511', 'Entulho/Retirada', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('LOURIVAL', '15 99702-5637', 'Entulho/Retirada', 'BEM RECOMENDADO, PEQUENAS QUANTIDADES (SAVEIRO)', 'NENHUMA RECLAMAÇÃO'),
('TONINHO', '15 99778-8684', 'Entulho/Retirada', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- CALHAS E TELHADOS
('ADALBERTO', '15 99115-3211', 'Calhas/Telhados', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ANDRÉ', '15 99829-7691', 'Calhas/Telhados', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('JAIRO', '15 99631-5507', 'Calhas/Telhados', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('OSVALDO SHIKOSKI', '15 99148-0707', 'Calhas/Telhados', 'BEM RECOMENDADO', '1 RECLAMAÇÃO'),
('REGINALDO', '11 99025-0460', 'Calhas/Telhados', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('MD-MARCELO', '15 99617-1618', 'Calhas/Telhados', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- CARRETO
('ABRAÃO - PORANGABA', '15 99719-0065', 'Carreto/Mudanças', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('SIMÃOZINHO - PORANGABA', '15 99602-6062', 'Carreto/Mudanças', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ZECA', '15 99792-9651', 'Carreto/Mudanças', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- CHAVEIRO
('ELISUR', '15 99799-9357', 'Chaveiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- ELETRODOMÉSTICOS
('REFRIGERAÇÃO GMM - GERALDO', '15 99739-6429', 'Conserto Eletrodomésticos', '', 'MUITAS RECLAMAÇÕES'),
('RÉGIS', '15 99709-0238', 'Conserto Eletrodomésticos', '', 'MUITAS RECLAMAÇÕES'),
('REFRILUX', '15 99705-5085', 'Conserto Eletrodomésticos', 'BEM RECOMENDADO, PREÇO JUSTO', 'NENHUMA RECLAMAÇÃO'),
('REFRIPOINT', '15 32596-904', 'Conserto Eletrodomésticos', 'BEM RECOMENDADO POR 2 MORADORES', 'NENHUMA RECLAMAÇÃO'),
('NIKOLAS', '15 99262-8164', 'Conserto Eletrodomésticos', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('SILVIO', '15 99601-0499', 'Conserto Eletrodomésticos', 'BEM RECOMENDADO POR 1 MORADOR', 'ALGUMAS RECLAMAÇÕES DO PASSADO'),
-- CONSTRUÇÃO
('ARI', '11 94339-7612', 'Construtor/Empreiteiro', '', 'BAIXA QUALIDADE, PEGOU O DINHEIRO E SUMIU'),
('ALVAN', '15 99793-7490', 'Construtor/Empreiteiro', '', 'CONSTRUÇÃO DE BAIXA QUALIDADE, NÃO DÁ RETORNO'),
('DAVID-DLAR', '11 99345-0740', 'Construtor/Empreiteiro', '', 'MUITAS RECLAMAÇÕES, CONSTRUÇÃO DE BAIXA QUALIDADE'),
('DUARTE CONSTRUÇÕES - YURE DUARTE', '15 99628-2739', 'Construtor/Empreiteiro', 'BEM RECOMENDADO POR 1 MORADOR', 'NENHUMA RECLAMAÇÃO'),
('GEAN HESSEL DE CAMARGO', '15 99851-9254', 'Construtor/Empreiteiro', '', 'NÃO CUMPRIU PRAZO E ABANDONOU A OBRA COM DINHEIRO PAGO'),
('GILENO', '11 97343-7130', 'Construtor/Empreiteiro', '', 'RECLAMAÇÃO DE TER RECEBIDO E NÃO TERMINAR O SERVIÇO'),
('JANUARIO', '15 99633-4126', 'Construtor/Empreiteiro', '', 'RECEBEU O DINHEIRO E NÃO TERMINOU O SERVIÇO'),
('JOEL', '15 99648-4985', 'Construtor/Empreiteiro', '', 'ATRASO E BAIXA QUALIDADE NO SERVIÇO'),
('JORGE PONCE', '15 99701-5998', 'Construtor/Empreiteiro', '', 'OBRA DE BAIXÍSSIMA QUALIDADE, MUITOS ERROS DE CONSTRUÇÃO'),
('MARIVALDO', '15 98129-8998', 'Construtor/Empreiteiro', '', 'RACHADURAS, FALTA DE ESTRUTURA, NÃO É ENGENHEIRO'),
('JOSÉ EDUARDO', '14 99158-2271', 'Construtor/Empreiteiro', 'MUITO BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('JOZÉ ANSELMO', '14 98205-3570', 'Construtor/Empreiteiro', 'MUITO BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('NOEL', '15 99642-1959', 'Construtor/Empreiteiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ROBSON SARTORI', '15 99742-1234', 'Construtor/Empreiteiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('RUDI CONSTRUÇÕES - FLÁVIO', '15 99667-8899', 'Construtor/Empreiteiro', 'BEM RECOMENDADO POR UNS', 'DEIXOU OBRA PELA METADE, PROPRIETÁRIO TEVE QUE CONTRATAR OUTRO'),
('TAVARES', '11 96463-5058', 'Construtor/Empreiteiro', '', 'DEIXOU A DESEJAR NO ACABAMENTO, DEMOROU E CAUSOU ESTRESSE'),
('RAFAEL MARTINS', '15 99236-1788', 'Construtor/Empreiteiro', '', 'PREJUÍZOS FINANCEIROS, RECEBEU E NÃO CUMPRIU'),
('VITINHO', '15 99667-1793', 'Construtor/Empreiteiro', '', 'NÃO CUMPRIU PRAZOS, RECEBEU E NÃO EXECUTOU. NÃO PAGUE ADIANTADO'),
('HÉLIO', '15 99615-9447', 'Construtor/Empreiteiro', 'BEM RECOMENDADO (CHURRASQUEIRA)', 'NENHUMA RECLAMAÇÃO'),
('ISMAEL', '15 99618-0594', 'Construtor/Empreiteiro', 'BEM RECOMENDADO (FOSSA)', 'NENHUMA RECLAMAÇÃO'),
('PEDRO MARTINS', '15 99724-4625', 'Construtor/Empreiteiro', 'CASA DO ZERO, ELÉTRICA, HIDRÁULICA, JACUZZI', 'NENHUMA RECLAMAÇÃO'),
-- CONTAINER
('ALUGMAK', '15 99809-3180', 'Container/Locação', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- CORRETAGEM
('ANA FLÁVIA - MORADORA', '11 99858-0521', 'Corretagem', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('FLÁVIO UCHOA', '15 99707-4587', 'Corretagem', '', 'RECLAMAÇÕES DIVERSAS'),
('GLOBAL IMÓVEIS - SIDNEY MELO', '15 98118-9558', 'Corretagem', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('GRACE MARTINS - MORADORA', '11 94202-9608', 'Corretagem', '', 'SEM SUPORTE PÓS-VENDA, MENTIRAS, AUMENTA VALOR PARA FAZER MARGEM'),
('JORGE PASSOS', '11 98466-998', 'Corretagem', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('MACEDO', '11 93423-3624', 'Corretagem', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('MARINA LEAL', '11 98194-0372', 'Corretagem', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('RUDI FERNANDES', '15 99604-4055', 'Corretagem', 'BEM RECOMENDADO COMO CORRETOR', 'NENHUMA RECLAMAÇÃO'),
-- CORTINAS
('L&L DECORAÇÕES - LÚCIA BUENO', '15 99690-8928', 'Cortinas/Persianas', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('GIANNI CORTINAS', '11 96192-7493', 'Cortinas/Persianas', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
-- DECKS/PERGOLADOS
('FOR NATURE WOODS - MARLENE', '15 99835-7496', 'Decks/Pergolados', '', 'DEU O GOLPE EM MUITOS MORADORES, FICOU COM DINHEIRO E NÃO ENTREGOU'),
('MOISÉS - SAO PAULO', '11 96820-4523', 'Decks/Pergolados', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('MOISÉS - INTERIOR', '15 99813-6384', 'Decks/Pergolados', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('RUDI', '15 99642-5522', 'Decks/Pergolados', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('CLAUDINEI', '15 99793-4468', 'Decks/Pergolados', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- DECORAÇÃO
('FABID''EVENTOS - FABIANA DADDATO', '11 96828-9852', 'Decoração de Festa', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
-- DEDETIZAÇÃO
('DADDATO SERVICE - WAGNER', '11 98865-8558', 'Dedetização/Marido de Aluguel', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- ELETRICISTA
('DANIEL BERNARDO', '15 99168-3245', 'Eletricista', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('FELIPE SALES', '15 98110-3449', 'Eletricista', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('GILSON', '15 99850-1390', 'Eletricista', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('JÚNIOR BALDASSIM', '15 99746-8987', 'Eletricista', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('LUCAS DE OLIVEIRA LEITE', '15 99701-5713', 'Eletricista', '', 'PEGOU O DINHEIRO E NÃO EXECUTOU O SERVIÇO'),
('MARQUINHOS', '14 99749-0550', 'Eletricista', '', 'VÁRIAS RECLAMAÇÕES: NÃO CUMPRE PRAZO, SEM PÓS-VENDA'),
('MILTON-MILCSOL', '14 99859-2345', 'Eletricista', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ELETRIK BOOST SOLAR - CLÁUDIA', '11 99855-5559', 'Energia Fotovoltaica', 'CUMPREM O QUE PROMETEM, BOM PÓS-VENDA', 'NENHUMA RECLAMAÇÃO'),
-- ENCANADOR / PEDREIRO
('ITAMAR', '11 96456-7674', 'Encanador/Pedreiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('JOSÉ ROBERTO - VICTÓRIA', '15 99160-4549', 'Encanador/Pedreiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('PAULO ROBERTO', '11 98543-0288', 'Encanador/Pedreiro', 'TRABALHAVA BEM NO INÍCIO', 'PASSOU A TERCEIRIZAR E A QUALIDADE FICOU MUITO RUIM'),
('DEIVID', '11 94129-9704', 'Encanador/Pedreiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- ENTULHO já inserido acima
-- ESQUADRIAS DE ALUMÍNIO
('ALBERTO', '14 81113-315', 'Esquadrias/Vidros', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ALUMIMAX - JOYCE OLIVEIRA', '14 99688-0779', 'Esquadrias/Vidros', '', 'NÃO RECOMENDADO, AMEAÇA DE PROCESSO AO RECLAMAR, PAGOU ADIANTADO E NÃO TERMINOU'),
('CAVALCANTI VIDROS', '15 99622-5627', 'Esquadrias/Vidros', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('EVANDRO', '15 99783-2072', 'Esquadrias/Vidros', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('FÉLIX', '15 99857-4994', 'Esquadrias/Vidros', '', 'DEMOROU 5 MESES E ENTREGOU COM PÉSSIMA VEDAÇÃO'),
('JOÃO NUNES - GUARULHOS', '11 99286-2521', 'Esquadrias/Vidros', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('JOEL - VIDROS', '15 99712-8879', 'Esquadrias/Vidros', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('MARCELO DC CAMARGO', '14 99805-9031', 'Esquadrias/Vidros', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('MORAES VIDROS - TATUÍ', '15 99650-1034', 'Esquadrias/Vidros', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('PARANÁ', '15 99771-2699', 'Esquadrias/Vidros', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('PAULO - VIDROS', '15 99635-2374', 'Esquadrias/Vidros', 'CUMPRE PRAZO E SÓ RECEBE NO TÉRMINO', 'NENHUMA RECLAMAÇÃO'),
('PEDRO - VIDROS', '14 99167-9222', 'Esquadrias/Vidros', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('RENOVO VIDRAÇARIA', '15 99765-4708', 'Esquadrias/Vidros', '', 'ATRASA ENTREGA. QUEBROU VIDROS INSTALADOS APÓS DISPUTA DE PAGAMENTO'),
('VIDROMAR - ALBERTO', '14 99739-7806', 'Esquadrias/Vidros', '', 'PEGOU OS CHEQUES E NÃO EXECUTOU O SERVIÇO. PÉSSIMO ATENDIMENTO'),
('VIDRAÇARIA ASTRAL - SILVANO', '15 99734-4693', 'Esquadrias/Vidros', 'TRABALHA BEM E PREÇO BOM', 'ATRASA MUITO A ENTREGA'),
-- FARMÁCIA
('TOP DROGARIA', '15 99847-1428', 'Farmácia', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('DROGARIA TOTAL - PORANGABA', '15 99817-1601', 'Farmácia', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- FAXINEIRA
('ANA FLÁVIA - FAXINEIRA', '15 99777-2270', 'Faxineira', '', 'VÁRIAS RECLAMAÇÕES (NÃO É CONFIÁVEL)'),
('DAIANA NUNES (DAI)', '15 99684-5691', 'Faxineira', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('DANIELE', '15 99832-9689', 'Faxineira', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('GABRIELA', '14 99855-3278', 'Faxineira', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('IARA', '15 99661-8031', 'Faxineira', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('KETHELIN', '15 99193-5447', 'Faxineira', '', 'VÁRIAS RECLAMAÇÕES'),
('LUCIANA', '15 99804-9820', 'Faxineira', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('MAYARA', '15 99686-7977', 'Faxineira', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('POLIANA', '15 99241-7247', 'Faxineira', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('ROSE', '15 98123-6463', 'Faxineira', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('SIRLENE', '11 95087-6122', 'Faxineira', 'BEM RECOMENDADA', 'NENHUMA RECLAMAÇÃO'),
('TALIA', '15 99137-9076', 'Faxineira', '', 'NÃO RECOMENDADA'),
-- FERRAMENTAS
('CASA DO CONSTRUTOR', '15 99830-4393', 'Ferramentas/Locação', 'BEM RECOMENDADO', 'RECLAMAÇÃO DE COBRANÇA POR MARTELETE QUE JÁ VEIO QUEBRADO'),
('FEMAC', '15 99848-1896', 'Ferramentas/Locação', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- FILTROS / HIDRÁULICA
('GILSON - FILTROS', '15 97403-2114', 'Filtros/Hidráulica', 'BEM RECOMENDADO NO INÍCIO', 'ALGUMAS RECLAMAÇÕES NO PÓS-VENDA'),
('RICARDO TROYA', '15 99832-6891', 'Filtros/Hidráulica', 'BEM RECOMENDADO', 'ALGUMAS RECLAMAÇÕES'),
('DIEGO', '15 99849-3643', 'Filtros/Hidráulica', '', 'NÃO RECOMENDADO POR 1 MORADOR'),
-- GESSEIRO
('FRANCISCO - CAWBOY', '11 91022-9909', 'Gesseiro', '', 'PÉSSIMO SERVIÇO, NÃO CONCLUIU, MORADORA TEVE QUE PAGAR OUTRO PARA REFAZER'),
('AF GESSOS - ADRIANO', '15 99815-6668', 'Gesseiro', '', 'PÉSSIMO SERVIÇO, NÃO CONCLUIU, TEVE QUE REFAZER TUDO'),
('MICHEL - GESSEIRO', '15 99853-8392', 'Gesseiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('POLY GESSO - SR. MANOEL', '11 99659-9282', 'Gesseiro', 'MUITO BEM RECOMENDADO', '2 RECLAMAÇÕES RECENTES SOBRE QUALIDADE DA MÃO DE OBRA'),
('GESSO TIETÊ - SÉRGIO SOUZA', '15 99853-8238', 'Gesseiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- INSTALAÇÕES
('EVERALDO', '15 99691-6893', 'Instalador/Box', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('LUCIANO', '15 99826-5681', 'Instalação/Porcelanato', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('SÉRGIO - PORCELANATO', '11 93283-3725', 'Instalação/Porcelanato', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('THIAGO - INSULFILME', '11 96106-3336', 'Insulfilme/Placas', 'MUITO BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- INTERNET
('ZAAZ', '0800 494-9999', 'Internet', 'A MELHOR DA REGIÃO', ''),
('FASTERNET', '0800 751-0091', 'Internet', 'BEM RECOMENDADO', ''),
-- HOTEL PET
('HAPPY TAIL ECO PET', '15 99136-4411', 'Hotel para Cachorro', 'BEM RECOMENDADO, CUIDADOS PÓS-OPERATÓRIOS', 'NENHUMA RECLAMAÇÃO'),
-- JARDINAGEM
('ALISSON MORADOR', '15 99609-4047', 'Jardinagem/Paisagismo', 'MUITO CAPRICHOSO, LIMPO E ORGANIZADO', '1 RECLAMAÇÃO'),
('AIRTON ALVES', '15 99740-4921', 'Jardinagem/Paisagismo', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('LAERTE', '15 99629-9336', 'Jardinagem/Paisagismo', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('LUÍS PARANÁ', '15 99739-3022', 'Jardinagem/Paisagismo', 'BEM RECOMENDADO', '1 RECLAMAÇÃO (DEIXOU SEM REGAR E NÃO PLANTOU)'),
('MOISÉS - JARDIM', '15 99848-3848', 'Jardinagem/Paisagismo', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('RAFAEL RICCI', '15 99140-1813', 'Jardinagem/Paisagismo', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('DANIEL VAZ', '15 99182-3854', 'Jardinagem/Piscina', 'BEM RECOMENDADO POR ALGUNS', 'PAGOU ADIANTADO E DEIXOU PLANTAS MORREREM, GROSSEIRO'),
('IVONETE E CLÓVIS', '15 99707-3559', 'Jardinagem/Piscina', 'BEM RECOMENDADOS NO INÍCIO', 'ALGUMAS RECLAMAÇÕES RECENTES'),
('JM-MATEUS', '15 99796-3275', 'Jardinagem/Piscina', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('PAULINHA', '15 99823-7302', 'Jardinagem/Piscina', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('RAFAEL ASSIS', '14 99861-3491', 'Jardinagem/Piscina', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ROBSON - JARDIM', '15 99623-9900', 'Jardinagem/Piscina', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ROGÉRIO E MICHELLE', '11 99873-2093', 'Jardinagem/Piscina', '', 'ALGUMAS RECLAMAÇÕES'),
('MARCELO - JPL', '15 99720-1066', 'Jardinagem/Piscina', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('GAÚCHO', '15 99817-4477', 'Jardinagem/Paisagismo', '', 'PAGOU 50% ADIANTADO E NÃO EXECUTOU O SERVIÇO'),
('GREEN GARDEN - CARLOS ROBERTO', '15 98113-2253', 'Jardinagem/Paisagismo', 'BEM RECOMENDADO POR ALGUNS', '2 RECLAMAÇÕES RECENTES POR NÃO TERMINAR OU DAR SUPORTE'),
('HOUSEKEEPING - ALEXANDRE', '11 99182-8734', 'Jardinagem/Paisagismo', '', 'NÃO MORA MAIS NO NINHO. PEGOU DINHEIRO E NÃO COMEÇOU OU NÃO TERMINOU PROJETOS'),
('SR. JOSÉ ANTÔNIO', '15 99848-8602', 'Jardinagem/Paisagismo', 'BEM RECOMENDADO NO INÍCIO', 'MUITAS CASAS, NÃO DÁ CONTA, DEIXA MORRER PLANTAS E É GROSSEIRO'),
-- LAVANDERIA
('5ASEC - TATUÍ', '15 33054-480', 'Lavanderia', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ACQUA - TATUÍ', '15 30226-722', 'Lavanderia', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- LIMPA FOSSA
('ÉRICA', '15 99834-1209', 'Limpa Fossa', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- HIGIENIZAÇÃO
('2TOK CLEAN', '15 99110-9735', 'Higienização/Estofados', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('ASTRA', '14 99647-8127', 'Higienização/Estofados', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('LIMPEZAÇÃO - GEOVANI', '15 99807-2866', 'Higienização/Estofados', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('A.C.N SOLUÇÕES - CARLOS', '15 99735-4691', 'Limpeza Pós-Obra', '', 'NÃO RECOMENDADO, APÓS RECLAMAÇÃO VOLTOU MAS FICOU SUJO. COBROU MAIS DE R$2000'),
('PANO CLEAN ESSENCIAL', '15 99620-4803', 'Limpeza Pós-Obra', 'BEM RECOMENDADO POR 1 MORADOR', 'NENHUMA RECLAMAÇÃO'),
-- MADEIREIRA
('MADEIREIRA SILVEIRA - EVANDRO', '15 99812-1094', 'Madeireira', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('MADEIREIRA CEDRO', '15 99617-3906', 'Madeireira', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- MARCENARIA
('JÚLIO - SORRAL', '15 97407-7674', 'Marcenaria/Planejados', '', 'MUITAS RECLAMAÇÕES DE QUEM PAGOU E NÃO RECEBEU. VÁRIAS AÇÕES JUDICIAIS'),
('MARCELO GALCHIN', '11 98042-3896', 'Marcenaria/Planejados', 'ENTREGA NO PRAZO, QUALIDADE, BOM PÓS-VENDA', 'NENHUMA RECLAMAÇÃO'),
('NOVA ALIANÇA PLANEJADOS', '15 99607-5983', 'Marcenaria/Planejados', '', 'GOLPE EM MUITOS MORADORES, FICOU COM O DINHEIRO E NÃO ENTREGOU'),
('REALEZA', '15 99642-1284', 'Marcenaria/Planejados', 'BEM RECOMENDADO POR 1 MORADOR', 'NENHUMA RECLAMAÇÃO'),
('SÃO RAFAEL MÓVEIS', '11 99688-9665', 'Marcenaria/Planejados', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- MÁRMORES
('ADNEY DAS PEDRAS - DANILO', '15 99739-3785', 'Mármores/Granitos', 'MUITO BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('CANAA - RÔMULO', '15 99642-8873', 'Mármores/Granitos', '', 'BAIXA QUALIDADE, DEVENDO PEÇAS PAGAS HÁ 1 ANO, NÃO RESPONDE'),
('PORTAL-JODNEY', '15 99650-6083', 'Mármores/Granitos', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('SANTA CRUZ - RODRIGO', '15 99716-7040', 'Mármores/Granitos', '', '1 RECLAMAÇÃO'),
-- MONTADOR DE MÓVEIS
('GUILHERME', '11 99951-4845', 'Montador de Móveis', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('DANILO - MONTADOR', '15 99713-9053', 'Montador de Móveis', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('GIL - MONTADOR', '15 99682-1780', 'Montador de Móveis', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- MÓVEIS DE VIME
('GIVANILDO - TATUÍ', '83 98104-107', 'Móveis de Vime', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
-- PEDREIRO
('GABRIEL - PEDREIRO', '11 95313-5607', 'Pedreiro', '', 'ATRASO NA ENTREGA, NÃO DÁ RETORNO, CAIU A QUALIDADE'),
('GILBERTO', '11 99608-5584', 'Pedreiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('CABELO - ANTONIO VICENTINI', '15 99600-5880', 'Pedreiro', 'BEM RECOMENDADO PARA REBOCO, MUROS, TELHADOS', 'NÃO RECOMENDADO PARA ACABAMENTO (PISOS, AZULEJOS) E LAJES'),
('JÚNIOR - PEDREIRO', '14 99139-8897', 'Pedreiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('MARCOS FARIAS', '11 96631-1550', 'Pedreiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('MARCOS SANTANA', '11 99957-8624', 'Pedreiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('JACKSON - PISOS', '11 94798-4699', 'Pedreiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('MODULARYS ENGENHARIA EMERSON', '11 97088-4009', 'Pedreiro', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO'),
('GILDÁSIO DO NASCIMENTO - GIL', '15 99805-4187', 'Pedreiro', '', 'NÃO RECOMENDADO'),
-- LIXEIRA
('ARTES FIBRA', '14 99774-7575', 'Lixeira Padrão', 'BEM RECOMENDADO', 'NENHUMA RECLAMAÇÃO')
ON CONFLICT (telefone_limpo) DO NOTHING;


-- =============================================
-- AVALIAÇÕES SEED
-- Usamos um usuário "sistema" temporário
-- IMPORTANTE: Substitua o UUID abaixo pelo ID real
-- de um usuário admin criado no Supabase Auth.
-- Por ora, inserimos via DO anonimo sem FK de morador
-- usando extensão pgcrypto para gerar UUIDs fictícios.
-- =============================================

-- Para popular avaliações, você pode rodar este bloco
-- após criar seu primeiro usuário admin no Supabase Auth
-- e substituir 'SEU-UUID-AQUI' pelo UUID do usuário:

/*
DO $$
DECLARE
  admin_id UUID := 'SEU-UUID-AQUI';  -- Substitua pelo UUID do seu usuário admin
BEGIN
  -- Exemplo: ROGÉRIO - nota 5
  INSERT INTO avaliacoes (morador_id, prestador_id, nota, observacao)
  SELECT admin_id, id, 5, 'Seed inicial - BEM RECOMENDADO'
  FROM prestadores WHERE telefone_limpo = '15991335780'
  ON CONFLICT DO NOTHING;

  -- ... (insira os demais seguindo o padrão)
END $$;
*/

-- ALTERNATIVA: Popular diretamente com UPDATE nas colunas obs_ da tabela prestadores
-- As observações já foram inseridas diretamente como campos obs_positiva/obs_negativa
-- e a view prestadores_com_media usa AVG real das avaliações.
-- Os dados de obs_positiva/obs_negativa são exibidos mesmo sem avaliações na tabela.
